ask_gusev/urls.py
from django.conf.urls import url
from django.contrib import admin

import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/?', views.login, name="login"),
    url(r'^question/(?P<question_id>[0-9]+)/$', views.question, name="question"),
    url(r'^tag/(?P<tag_title>.+)/$', views.tag, name="tag"),
    url(r'^hot/$', views.hot, name="hot"),
    url(r'^settings/?', views.settings, name="settings"),
    url(r'^signup/?', views.signup, name="signup"),
    url(r'^ask/?', views.ask, name="ask"),
    url(r'^$', views.index, name='index'),

]

ask_gusev/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.db.models import Count, Sum


class Profile(models.Model):
    user = models.OneToOneField(User)
    avatar = models.ImageField(upload_to='uploads')
    info = models.TextField()

    class Meta:
        verbose_name = u'Профиль'
        verbose_name_plural = u'Профили'


class TagManager(models.Manager):
    def count_questions(self):
        return self.annotate(questions_count=Count('question'))

    def order_by_count(self):
        return self.count_questions().order_by('-questions_count')

    def get_by_title(self, title):
        return self.get(title=title)

    def get_or_create(self, title):
        try:
            tag = self.get_by_title(title)
        except Tag.DoesNotExist:
            tag = self.create(title=title)
        return tag

    def count_popular(self):
        questions_count = Count('question')

        return self.order_by_count().all()[:10]


class Tag(models.Model):
    title = models.CharField(max_length = 15)
    objects = TagManager()

    class Meta:
        verbose_name = u'Тэг'
        verbose_name_plural = u'Тэги'

    def get_url(self):
        return '/tag/' + self.title

    def __str__(self):
        return str(self.title)

    def __unicode__(self):
        return str(self.title)


class QuestionManager(models.Manager):

    def new(self):
        return self.order_by('-date')

    def hot(self):
        return self.order_by('-rating')

    def tag(self, tag):
        return self.filter(tags=tag)


class Question(models.Model):
    title = models.CharField(max_length=50)
    text = models.TextField()
    author = models.ForeignKey(User)
    date = models.DateTimeField()
    tags = models.ManyToManyField(Tag)
    rating = models.IntegerField(default=0)

    objects = QuestionManager()

    class Meta:
        verbose_name = u'Вопрос'
        verbose_name_plural = u'Вопросы'
        ordering = ['-date']

    def get_answers(self):
        return Answer.objects.filter(question_id=self.id)

    def __str__(self):
        return str(self.title)

    def __unicode__(self):
        return str(self.title)


# class QuestionRatingManager(models.Manager):
#
#     def calculate(self, question):
#         return self.filter(question=question).aggregate(sum=Sum('value'))['sum']
#
#     def update(self, author, question, value):
#         obj, new = self.update_or_create(
#             author=author,
#             question=question,
#             defaults={'value': value}
#         )
#
#         question.rating = self.calculate(question)
#         question.save()
#
#         return new
#
#
# class QuestionRating(models.Model):
#     PLUS = 1
#     MINUS = -1
#
#     question = models.ForeignKey(Question)
#     author = models.ForeignKey(User)
#     value = models.SmallIntegerField(default=1)
#
#     objects = QuestionLikeManager()


class Answer(models.Model):
    text = models.TextField()
    question = models.ForeignKey(Question)
    author = models.ForeignKey(User)
    date = models.DateTimeField(default=timezone.now)
    correct = models.BooleanField(default=False)
    rating = models.IntegerField(default=0)

    class Meta:
        verbose_name = u'Ответ'
        verbose_name_plural = u'Ответы'
        ordering = ['-correct', 'date', '-rating']

    def get_url(self):
        return self.question.get_url()


# class AnswerRatingManager(models.Manager):
#     def calculate(self, answer):
#         return self.filter(answer=answer).aggregate(sum=Sum('value'))['sum']
#
#     def update(self, author, answer, value):
#         obj, new = self.update(
#             author=author,
#             answer=answer,
#             defaults={'value':value}
#         )
#
#         answer.rating = self.calculate(answer)
#         answer.save()
#
#         return new
#
#
# class AnswerRating(models.Model):
#     PLUS = 1
#     MINUS = -1
#
#     answer = models.ForeignKey(Answer)
#     author = models.ForeignKey(User)
#     value = models.SmallIntegerField(default=1)
#
#     objects = AnswerRatingManager()

ask_gusev/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from collections import namedtuple
import models


def get_page(request):
    page = request.GET.get('page')
    if page is None or not page.isdigit():
        page = 1
    else:
        page = int(page)

    return page


# STANDART DJANGO PAGINATOR
def pagination(request, object_list, per_page=2, page=1):

    max_page = len(object_list.questions) // per_page
    if len(object_list.questions) % per_page != 0:
        max_page += 1

    if page > max_page:
        current_page = 1
        if per_page > len(object_list.questions):
            questions_to_render = object_list.questions
        else:
            questions_to_render = object_list.questions[:per_page]
    else:
        current_page = page
        questions_to_render = object_list.questions[per_page * (page - 1): per_page * (page)]

    next_page = current_page + 1
    prev_page = current_page - 1

    prev_max_page = max_page - 1
    prev_prev_max_page = prev_max_page - 1

    if current_page == 1:
        prev_page = 1
    if per_page * current_page >= len(object_list.questions):
        next_page = current_page
    context = {'questions' : questions_to_render, 'current_page' : current_page,
               'next_page' : next_page, 'prev_page' : prev_page, 'max_page' : max_page,
               'prev_max_page' : prev_max_page, 'prev_prev_max_page' : prev_prev_max_page,
               'tag' : object_list.tag, 'hot' : object_list.hot}
    return render(request, object_list.template, context)


def index(request):

    object_list = namedtuple('hot', 'tag', 'questions', 'template')

    page = get_page(request)

    object_list.questions = models.Question.objects.all()
    object_list.template = "index.html"
    object_list.tag = None
    object_list.hot = False

    return pagination(request, object_list, page=page)


def login(request):
    return render(request, "login.html")


def signup(request):
    return render(request, "signup.html")


def settings(request):
    return render(request, "settings.html")


def ask(request):
    return render(request, "ask.html")


def tag(request, tag_title):
    tag_id = models.Tag.objects.get_by_title(tag_title).id
    object_list = namedtuple('hot', 'tag', 'questions', 'template')
    object_list.hot = False
    object_list.questions = models.Question.objects.tag(tag_id)
    object_list.template = "index.html"
    object_list.tag = tag_title
    return pagination(request, object_list)


def hot(request):
    object_list = namedtuple('hot', 'tag', 'questions', 'template')
    object_list.hot = True
    object_list.tag = None
    object_list.template = "index.html"
    object_list.questions = models.Question.objects.hot()
    page = request.GET.get('page')
    if page is None or not page.isdigit():
        page = 1
    else:
        page = int(page)

    return pagination(request, object_list, page=page)


def question(request, question_id):
    question = models.Question.objects.get(id=question_id)
    answers = question.get_answers()

    return render(request, "question.html", {"object": question, "answers": answers})

templates/answer_form.html
<textarea rows = 10 class="ask-text" placeholder="Enter your answer here" name=answer-form></textarea>
<button style = "margin-bottom: 5px" type="button" class="btn btn-basic search-btn" name=answer-question>Ask!</button>

templates/ask.html
{% extends "base.html" %}

{% load static %}

{% block title %}
    <title>Ask</title>
{% endblock title %}

{% block stylesheet %}
    <link href="{% static "/css/ask.css" %}" rel="stylesheet">
{% endblock stylesheet %}

{% block content %}
    <h1>New Question</h1>
    <div class="alert alert-danger">
      <strong>Warning!</strong> You entered incorrect data!
    </div>

    <div class="container question-form" style="width: 100%">
        <div class="row">
            <div class="col-md-2">
                Title
            </div>
            <div class="col-md-10">
            <input type="text" class="ask-title" placeholder="Your question title">
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">
                Text
            </div>
            <div class="col-md-10">
                <textarea  cols= "40" rows = 10 class="ask-text" placeholder="Your question"></textarea>
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">
                Tags
            </div>
            <div class="col-md-10">
                <input type="text" class="ask-tags" placeholder="Tags">
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">
            </div>
            <div class="col-md-10">
                <button type="button" class="btn btn-info search-btn" name=ask-question>Ask!</button>
            </div>
        </div>


    </div>
{% endblock content %}

templates/base.html
<!DOCTYPE html>

<html lang="ru">
{% load static %}

<head>
    {% block header %}
        <meta charset="utf-8">

        {% block title %}
            <title>Base</title>
        {% endblock title %}

        <link rel="stylesheet" type="text/css" href="{% static "/css/bootstrap.min.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "/css/base.css" %}">

        {% block stylesheet %}
        {% endblock stylesheet %}

        {% block style %}
        {% endblock style %}

        {% block js %}
        {% endblock js %}

    {% endblock header %}
</head>

<body>

<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'index' %}">
                <img class="logo" src="{% static "/img/logo.png" %}">
            </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav search-group">
                <li><input type="text" class="form-control"  placeholder="Search" ></li>
                <li><button type="button" class="btn btn-success search-btn">Ask!</button></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><img class="avatar" src="{{ user.profile_set.avatar.url }}" alt="avatar"></li>
                    <li>
                        <ul class="profile-navbar">
                            <li>{{ user.first_name }} {{ user.last_name }}</li>
                            <li><a href="{% url 'settings' %}">Settings</a> <a href="#">Log out</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'login' %}">Log in</a></li>
                    <li><a href="{% url 'signup' %}">Register</a></li>
                {% endif %}
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

<div class="container">

    <div class="col-md-9">
        {% block content %}
        {% endblock content %}
    </div>

    <div class="col-md-3">
        <h1>Popular tags</h1>

        <ul class="container-fluid tags">
            <li class="tags-list"><a style="color: red" href="#">perl</a></li>
            <li class="tags-list"><a style="color: blue" href="#">python</a></li>
            <li class="tags-list"><a style="color: orange" href="#">TechnoPark</a></li>
            <li class="tags-list"><a style="color: cyan" href="#">MySQL</a></li>
            <li class="tags-list"><a style="color: grey" href="#">django</a></li>
            <li class="tags-list"><a style="color: violet" href="#">Mail.ru</a></li>
            <li class="tags-list"><a style="color: green" href="#">Voloshin</a></li>
            <li class="tags-list"><a style="color: orange" href="#">Firefox</a></li>
        </ul>
        <h1>Best members</h1>
        <p>
            <ul class="member-list">
                <li><a href="#">Vincent Vega</a></li>
                <li><a href="#">Robert Kelso</a></li>
                <li><a href="#">Ryan Gosling</a></li>
                <li><a href="#">Michael Douglas</a></li>
                <li><a href="#">Pavel Durov</a></li>
            </ul>
        </p>
    </div>
</div>

</body>

<footer>
    <div class="jumbotron footer"><strong>Mikhail Gusev, 2016</strong></div>
</footer>
</html>

templates/index.html
{% extends "base.html" %}

{% load static %}

{% block title %}
<title>Index</title>
{% endblock title %}

{% block stylesheet %}
    <link rel="stylesheet" type="text/css" href="{% static "/css/index.css" %}">
{% endblock stylesheet %}


{% block content %}
    {% if hot %}
        <h1 style="display:inline">Hot Questions</h1>
        <a href="{% url 'index' %}" style="margin-left:10px">New Questions</a>
    {% else %}
        {% if tag is None %}
            <h1 style="display:inline">New Questions</h1>
            <a href="{% url 'hot' %}" style="margin-left:10px">Hot Questions</a>
        {% else %}
            <h1 style="display:inline">Tag: {{ tag.title }} </h1>
        {% endif %}
    {% endif %}

    <div style="width: 100%" class = "container questions-container">
        {% for object in questions %}
            {% include "single_question.html" %}
        {% endfor %}
    </div>

    {% include "paginator.html" %}
{% endblock content %}

templates/login.html
{% extends "base.html" %}

{% load static %}

{% block title %}
    <title>Login</title>
{% endblock title %}

{% block stylesheet %}
    <link href="{% static "/css/login.css" %}" rel="stylesheet">
{% endblock stylesheet %}

{% block content %}
    <h1>Log In</h1>

    <div class="alert alert-danger">
        <strong>Warning!</strong> Incorrect login or password!
    </div>

    <div class="container question-form" style="width: 100%">
        <div class="row">
            <div class="col-md-2">
                Login
            </div>
            <div class="col-md-10">
                <input type="text" class="login"> <span style="color:red"> incorrect data!</span>
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">
                Password
            </div>
            <div class="col-md-10">
                <input type="password" class="password">
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">
            </div>
            <div class="col-md-10">
                <button type="button" style="margin-left:0; margin-top: 10px" class="btn btn-basic search-btn" name=login>Log in!</button>
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">
            </div>
            <div class="col-md-10">
                <a style="margin-top: 10px" href="{% url 'signup' %}">create new account</a>
            </div>
        </div>
    </div>
{% endblock content %}

templates/paginator.html
<ul class="pagination" style = "margin-left: 15px">

        <li><a class="pagination" href="?page={{ prev_page }}" > << </a></li>
        <li><a class="pagination" href="?page=1">1</a></li>
        {% if max_page > 1 %}
            <li><a class="pagination" href="?page=2">2</a></li>
            {% if current_page > 4 %}
                <li><a class="pagination" >..</a></li>
            {% endif %}

            {% if current_page > 3 %}
                <li><a class="pagination" href="?page={{ prev_page }}" > {{ prev_page }}</a></li>
            {% endif %}

            {% if current_page > 2 %}
                <li><a class="pagination" href="?page={{ current_page }}" > {{ current_page }}</a></li>
            {% endif %}

            {% if current_page != max_page and current_page > 1 %}
                <li><a class="pagination" href="?page={{ next_page }}" > {{ next_page }}</a></li>
            {% endif %}

            {% if prev_prev_max_page > next_page %}
                <li><a class="pagination" >..</a></li>
            {% endif %}

            {% if prev_max_page > next_page %}
                <li><a class="pagination" href="?page={{ prev_max_page }}">{{ prev_max_page }}</a></li>
            {% endif %}

            {% if max_page > next_page %}
                <li><a class="pagination" href="?page={{ max_page }}">{{ max_page }}</a></li>
            {% endif %}
        {% endif %}
        <li><a class="pagination" href="?page={{ next_page }}"> >> </a></li>
</ul>

templates/question.html
{% extends "base.html" %}

{% load static %}

{% block title %}
    <title>Question</title>
{% endblock title %}

{% block stylesheet %}
    <link href="{% static "/css/index.css" %}" rel="stylesheet">
    <link href="{% static "/css/question.css" %}" rel="stylesheet">
{% endblock stylesheet %}

{% block content %}
    {% include "single_question.html" %}

    <hr>
        <ul class="answer-list">
            {% for object in answers %}
                {% include "single_answer.html" %}
            {% endfor %}
        </ul>
    <hr>

    {% if user.is_authenticated and user.id != object.author_id %}
        {% include "answer_form.html" %}
    {% endif %}
{% endblock content %}

templates/rating_btn.html
<span>
    <span>
        <button class="btn btn-xs btn-success">
            <i class="glyphicon glyphicon-plus"></i>
        </button>
    </span>

    <span style="width: 20px; color: green;"> {{ object.rating }} </span>

    <span>
        <button class="btn btn-xs btn-danger">
            <i class="glyphicon glyphicon-minus"></i>
        </button>
    </span>
</span>

templates/settings.html
{% extends "base.html" %}

{% load static %}

{% block title %}
    <title>Settings</title>
{% endblock title %}

{% block stylesheet %}
      <link href="{% static "css/settings.css" %}" rel="stylesheet">
{% endblock stylesheet %}

{% block content %}
<h1>Settings: {{ user.first_name }} {{ user.last_name }}</h1>
<div class="alert alert-danger">
  <strong>Warning!</strong> You entered incorrect data!
</div>
<div class="container question-form" style="width: 100%">
    <div class="row">
        <div class="col-md-2">
            Login
        </div>
        <div class="col-md-10">
            <input type="text" class="settings-login" placeholder="{{ user.username }}">
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            Email
        </div>
        <div class="col-md-10">
            <input type="text" class="settings-email" placeholder="{{ user.email }}">
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            Nickname
        </div>
        <div class="col-md-10">
            <input type="text" class="settings-nickname" placeholder="{{ user.first_name }} {{ user.last_name }}">
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            Upload avatar
        </div>
        <div class="col-md-10">
            <img class="avatar-upload" src="{{ user.profile.avatar }}">
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-10 choose-avatar">
            <input type="file">
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-10">
            <button type="button" style="margin-left:0; margin-top: 20px" class="btn btn-basic search-btn" name=answer-question>Save</button>
        </div>
    </div>
</div>
{% endblock content %}

templates/signup.html
{% extends "base.html" %}

{% load static %}

{% block title %}
    <title>Sign up</title>
{% endblock title %}

{% block stylesheet %}
    <link href=" {% static "/css/signup.css" %}" rel="stylesheet">
{% endblock stylesheet %}

{% block content %}
    <h1>Sign Up</h1>
    <div class="alert alert-danger">
      <strong>Warning!</strong> This e-mail adress is already in use!
    </div>

    <div class="container question-form" style="width: 100%">
        <div class="row">
            <div class="col-md-2">
                Login
            </div>
            <div class="col-md-10">
                <input type="text" class="login">
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">
                Email
            </div>
            <div class="col-md-10">
                <input type="text" class="e-mail">
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">
                NickName
            </div>
            <div class="col-md-10">
                <input type="text" class="nickname">
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">
                Password
            </div>
            <div class="col-md-10">
                <input type="password" class="password">
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">
                Repeat password
            </div>
            <div class="col-md-10">
                <input type="password" class="password">
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">
                Upload avatar
            </div>
            <div class="col-md-10 choose-avatar">
                <input type="file">
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">
            </div>
            <div class="col-md-10">
                <button type="button" style="margin-left:0; margin-top: 10px" class="btn btn-basic search-btn" name=register>Register!</button>
            </div>
        </div>

    </div>
{% endblock content %}

templates/single_answer.html
{% load static %}

<div class="container question-box">
    <div class="col-md-2">
        <ul style = "list-style: none; margin-left: -50px; margin-bottom: 10px; margin-top: -5px">
            <li><img style="width: 100px" src="{% static "/img/def_avatar.png" %}" alt="avatar"></li>
            <li style = "margin-left: 15px">{% include "rating_btn.html" %}</li>
        </ul>
    </div>

    <div class="col-md-10 question-data">
        <p style="margin-top: 10px">{{ object.text }}</p>
        <input type="checkbox">  Correct!<br>
    </div>
</div>

templates/single_question.html
{% load static %}

<div class="container question-box">
    <div class="col-md-3">
        <ul style = "list-style: none; margin-left: -50px; margin-bottom: 10px; margin-top: -5px"">
            <li><img style="width: 100px" src="{% static '/img/def_avatar.png' %}" alt="avatar"></li>
            <li style = "margin-left: 15px">{% include "rating_btn.html" %}</li>
        </ul>
    </div>

    <div class="col-md-9 question-data">
        <a class="question-header" href="{% url 'question' object.id %}"> {{ object.title }}</a>
        <p> {{ object.text }} </p>
        <a href="{% url 'question' object.id %}">Answers ({{ object.get_answers.count }})</a>
        <span style="margin-left: 15px">Tags:</span>
        <ul class="question-tags">
            {% for tag in object.tags.all %}
                <li><a href="{% url 'tag' tag.title %}"> {{ tag.title }} </a></li>
            {% endfor %}
        </ul>
    </div>
</div>